### ISSUE TITLE
Download one file from a set of expressions

### ISSUE THREAD

**Issue by 0xC4N1** [marklieberman/downloadstar#43]
Since the recent update that came with a new UI, selecting a single file from a set of expressions doesn't seem to work as it used to be anymore.

I was using Download Star to quickly download the image with the largest resolution from a site that contained an image in different resolutions. It was possible to accomplish this by providing this regular expression: `o_d.jpg|_k.jpg|o_d.png`

In case the original resolution `o_d.jpg` was not available, it would select the smaller resolution `_k.jpg`. In case both resolution where available, Download Star selected only the original resolution. However now it selects both `o_d.jpg` and_`k.jpg`.

How can I accomplish this with the new UI?

**Comment by marklieberman** [comment]
I believe this feature of only selecting 1 image was actually a matching bug in that was fixed before the new UI. It was never intended to work that way as that regex should check all matching files.

There is currently no way to do priority matching. I suggest clicking the "show only checked items" button and manually deselecting the low resolution matches.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by 0xC4N1** [comment]
Thank you for your quick reply. I've downgraded to v1.0.2 via https://addons.mozilla.org/de/firefox/addon/download-star/versions/ now and it is working as expected again. 

I'm gonna disable the auto update until this feature is implemented again. Would be great if you could comment here if you're gonna implement a priority selecting switch.

**Comment by marklieberman** [comment]
Out of curiosity, do you have both links and embeds enabled on the bottom left? Usually, the high resolution file is linked from a low resolution thumbnail. If so, just un-select the embeds button to see only the linked highres files.

**Comment by 0xC4N1** [comment]
No that doesn't fix it. Both resolutions are linked so both get auto selected in v2. But being able to select embedded and linked files at once is a great solution. Enabling to use priority selection would make it perfect.

**Comment by 0xC4N1** [comment]
I was going to provide a sample page but I've just noticed the actual issue. It is not the fast filter that matches too many images, it is the built in images filter checkbox that is always enabled when I reopen Download Star v2. Is it possible to keep the last state of the elements? I just need the fast filter and the media sources.

**Comment by 0xC4N1** [comment]
Never mind. It keeps the last state once you've started a download. :)

**Comment by marklieberman** [comment]
The popup by default only saves changes to the controls if you hit Download. To make it save all changes immediately, enable it in the options:

![image](https://user-images.githubusercontent.com/6473247/42656457-57fcd276-85ed-11e8-8587-11cadb3d4dc7.png)

In both cases, it saves the state of the built-in filters properly for me when I test it.

**Comment by 0xC4N1** [comment]
Ah now I see it. My mind didn't notice there is another setting so close to the headline above the first input field. The built in filters save their state without downloading only when the save immediately setting is enabled. Seems to be working as it is supposed to be. Thank you for spending your time.
